# Run a classifer on the branchwater search output

In [1]:
# base checkout of workflow directory is here:
BASE='/home/ctbrown/scratch3/2025-workflow-core99/'

# parquet files from branchwater
#BASE_OUTPUTS=BASE+'/outputs.branchwater'

MIN=90
SCALED=1000
HASH_THRESHOLD=int(30000 / SCALED)

CORENAMES = set([ x.strip() for x in open(BASE + 'inputs.mapping/names.list') ])
print(len(CORENAMES))

#BASE_OUTPUTS=BASE+f'/outputs.mapping/cds/singlehash.k21/outputs.branchwater.min{MIN}.scaled{SCALED}'
BASE_OUTPUTS=BASE+'/outputs.cds/branchwater.cds3'

15

In [2]:
import polars as pl
import numpy as np
import sklearn.tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold

In [3]:
dirpath = BASE_OUTPUTS+'/*.parquet'

bw_df = pl.scan_parquet(dirpath).collect()
bw_df = bw_df.with_columns(pl.col("query_name").alias("species"),
                           pl.col("match_name").alias("acc"))
bw_df = bw_df.select(["species", "acc", "containment", "intersect_hashes"])

# mimic the Web site search threshold of 0.1
bw_df = bw_df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)
bw_df = bw_df.filter(pl.col("species").is_in(CORENAMES))
bw_df

shape: (626_481, 4)
┌────────────────────────────┬─────────────┬─────────────┬──────────────────┐
│ species                    ┆ acc         ┆ containment ┆ intersect_hashes │
│ ---                        ┆ ---         ┆ ---         ┆ ---              │
│ str                        ┆ str         ┆ f64         ┆ i64              │
╞════════════════════════════╪═════════════╪═════════════╪══════════════════╡
│ s__Bariatricus sp004560705 ┆ ERR2241669  ┆ 0.504614    ┆ 1531             │
│ s__Bariatricus sp004560705 ┆ ERR2241674  ┆ 0.504614    ┆ 1531             │
│ s__Bariatricus sp004560705 ┆ SRR11185229 ┆ 0.488134    ┆ 1481             │
│ s__Bariatricus sp004560705 ┆ SRR9866666  ┆ 0.479235    ┆ 1454             │
│ s__Bariatricus sp004560705 ┆ SRR11185232 ┆ 0.478906    ┆ 1453             │
│ …                          ┆ …           ┆ …           ┆ …                │
│ s__UBA2868 sp004552595     ┆ SRR16702778 ┆ 0.004763    ┆ 30               │
│ s__UBA2868 sp004552595     ┆ SRR6811659  ┆ 0.004763    ┆ 30               │
│ s__UBA2868 sp004552595     ┆ SRR26991454 ┆ 0.004763    ┆ 30               │
│ s__UBA2868 sp004552595     ┆ SRR7648335  ┆ 0.004763    ┆ 30               │
│ s__UBA2868 sp004552595     ┆ SRR12349269 ┆ 0.004763    ┆ 30               │
└────────────────────────────┴─────────────┴─────────────┴──────────────────┘

In [4]:
bw_df['species'].n_unique()

15

In [5]:
metadata_df = pl.scan_parquet('/group/ctbrowngrp5/sra-metagenomes/20241128-metadata.parquet')
metadata_df = metadata_df.select(["acc", "organism", "assay_type"])\
    .filter(pl.col("acc") != "NP")\
    .filter(pl.col("assay_type") == "WGS")

metadata_df = metadata_df.collect()
metadata_df

shape: (703_916, 3)
┌─────────────┬───────────────────────┬────────────┐
│ acc         ┆ organism              ┆ assay_type │
│ ---         ┆ ---                   ┆ ---        │
│ str         ┆ str                   ┆ str        │
╞═════════════╪═══════════════════════╪════════════╡
│ SRR28523869 ┆ human metagenome      ┆ WGS        │
│ SRR19901137 ┆ Streptococcus suis    ┆ WGS        │
│ SRR24962475 ┆ Escherichia coli      ┆ WGS        │
│ SRR29161330 ┆ biofilm metagenome    ┆ WGS        │
│ SRR26668739 ┆ bovine gut metagenome ┆ WGS        │
│ …           ┆ …                     ┆ …          │
│ ERR4174288  ┆ human gut metagenome  ┆ WGS        │
│ ERR3160109  ┆ human gut metagenome  ┆ WGS        │
│ ERR2709457  ┆ human gut metagenome  ┆ WGS        │
│ ERR2709367  ┆ human gut metagenome  ┆ WGS        │
│ ERR2709388  ┆ human gut metagenome  ┆ WGS        │
└─────────────┴───────────────────────┴────────────┘

In [6]:
bw_df = bw_df.join(metadata_df, on="acc", how="left")
bw_df

shape: (626_481, 6)
┌───────────────────┬─────────────┬─────────────┬──────────────────┬──────────────────┬────────────┐
│ species           ┆ acc         ┆ containment ┆ intersect_hashes ┆ organism         ┆ assay_type │
│ ---               ┆ ---         ┆ ---         ┆ ---              ┆ ---              ┆ ---        │
│ str               ┆ str         ┆ f64         ┆ i64              ┆ str              ┆ str        │
╞═══════════════════╪═════════════╪═════════════╪══════════════════╪══════════════════╪════════════╡
│ s__Bariatricus    ┆ ERR2241669  ┆ 0.504614    ┆ 1531             ┆ metagenome       ┆ WGS        │
│ sp004560705       ┆             ┆             ┆                  ┆                  ┆            │
│ s__Bariatricus    ┆ ERR2241674  ┆ 0.504614    ┆ 1531             ┆ metagenome       ┆ WGS        │
│ sp004560705       ┆             ┆             ┆                  ┆                  ┆            │
│ s__Bariatricus    ┆ SRR11185229 ┆ 0.488134    ┆ 1481             ┆ pig gut          ┆ WGS        │
│ sp004560705       ┆             ┆             ┆                  ┆ metagenome       ┆            │
│ s__Bariatricus    ┆ SRR9866666  ┆ 0.479235    ┆ 1454             ┆ Lawsonia         ┆ WGS        │
│ sp004560705       ┆             ┆             ┆                  ┆ intracellularis  ┆            │
│ s__Bariatricus    ┆ SRR11185232 ┆ 0.478906    ┆ 1453             ┆ pig gut          ┆ WGS        │
│ sp004560705       ┆             ┆             ┆                  ┆ metagenome       ┆            │
│ …                 ┆ …           ┆ …           ┆ …                ┆ …                ┆ …          │
│ s__UBA2868        ┆ SRR16702778 ┆ 0.004763    ┆ 30               ┆ synthetic        ┆ WGS        │
│ sp004552595       ┆             ┆             ┆                  ┆ metagenome       ┆            │
│ s__UBA2868        ┆ SRR6811659  ┆ 0.004763    ┆ 30               ┆ mangrove         ┆ WGS        │
│ sp004552595       ┆             ┆             ┆                  ┆ metagenome       ┆            │
│ s__UBA2868        ┆ SRR26991454 ┆ 0.004763    ┆ 30               ┆ estuary          ┆ WGS        │
│ sp004552595       ┆             ┆             ┆                  ┆ metagenome       ┆            │
│ s__UBA2868        ┆ SRR7648335  ┆ 0.004763    ┆ 30               ┆ marine sediment  ┆ WGS        │
│ sp004552595       ┆             ┆             ┆                  ┆ metagenome       ┆            │
│ s__UBA2868        ┆ SRR12349269 ┆ 0.004763    ┆ 30               ┆ aquatic          ┆ WGS        │
│ sp004552595       ┆             ┆             ┆                  ┆ metagenome       ┆            │
└───────────────────┴─────────────┴─────────────┴──────────────────┴──────────────────┴────────────┘

In [7]:
bw_df['organism'].value_counts().sort(by='count', descending=True)

shape: (467, 2)
┌────────────────────────────┬────────┐
│ organism                   ┆ count  │
│ ---                        ┆ ---    │
│ str                        ┆ u32    │
╞════════════════════════════╪════════╡
│ human gut metagenome       ┆ 215125 │
│ pig gut metagenome         ┆ 75728  │
│ null                       ┆ 59713  │
│ gut metagenome             ┆ 53600  │
│ metagenome                 ┆ 42370  │
│ …                          ┆ …      │
│ lichen crust metagenome    ┆ 1      │
│ Odoribacter laneus         ┆ 1      │
│ snake metagenome           ┆ 1      │
│ Balaenoptera acutorostrata ┆ 1      │
│ ecological metagenomes     ┆ 1      │
└────────────────────────────┴────────┘

In [33]:
rename_df = []
for organism in bw_df['organism'].unique().to_list():
    simpleorg = 'unknown'
    if organism:
        for kw in ['human', 'homo']:
            if kw in organism.lower():
                simpleorg = 'human'
                break
        for kw in ['pig', 'sus', 'scrofa']:
            if kw in organism.lower():
                simpleorg = 'pig'
                break
    rename_df.append(dict(organism=organism, simpleorg=simpleorg))

rename_df = pl.DataFrame(rename_df)
rename_df['simpleorg'].value_counts().sort(by='count', descending=True)

shape: (3, 2)
┌───────────┬───────┐
│ simpleorg ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ unknown   ┆ 190   │
│ human     ┆ 14    │
│ pig       ┆ 2     │
└───────────┴───────┘

In [34]:
rename_df

shape: (206, 2)
┌───────────────────────┬───────────┐
│ organism              ┆ simpleorg │
│ ---                   ┆ ---       │
│ str                   ┆ str       │
╞═══════════════════════╪═══════════╡
│ peat metagenome       ┆ unknown   │
│ mine metagenome       ┆ unknown   │
│ cow dung metagenome   ┆ unknown   │
│ human oral metagenome ┆ human     │
│ unidentified          ┆ unknown   │
│ …                     ┆ …         │
│ sheep gut metagenome  ┆ unknown   │
│ coral metagenome      ┆ unknown   │
│ skin metagenome       ┆ unknown   │
│ outdoor metagenome    ┆ unknown   │
│ freshwater metagenome ┆ unknown   │
└───────────────────────┴───────────┘

In [35]:
# add a new column with a simplified organism
bw_df = bw_df.join(rename_df, on='organism', how='inner', coalesce=True).select(['acc', 'organism', 'species', 'simpleorg'])
bw_df.select(['acc', 'simpleorg']).unique()['simpleorg'].value_counts()

shape: (3, 2)
┌───────────┬────────┐
│ simpleorg ┆ count  │
│ ---       ┆ ---    │
│ str       ┆ u32    │
╞═══════════╪════════╡
│ unknown   ┆ 74058  │
│ pig       ┆ 7029   │
│ human     ┆ 128574 │
└───────────┴────────┘

In [36]:
bw_df

shape: (537_963, 4)
┌─────────────┬────────────────────────────┬────────────────────────────┬───────────┐
│ acc         ┆ organism                   ┆ species                    ┆ simpleorg │
│ ---         ┆ ---                        ┆ ---                        ┆ ---       │
│ str         ┆ str                        ┆ str                        ┆ str       │
╞═════════════╪════════════════════════════╪════════════════════════════╪═══════════╡
│ ERR2241669  ┆ metagenome                 ┆ s__Bariatricus sp004560705 ┆ unknown   │
│ ERR2241674  ┆ metagenome                 ┆ s__Bariatricus sp004560705 ┆ unknown   │
│ SRR11185229 ┆ pig gut metagenome         ┆ s__Bariatricus sp004560705 ┆ pig       │
│ SRR11185232 ┆ pig gut metagenome         ┆ s__Bariatricus sp004560705 ┆ pig       │
│ SRR8960383  ┆ pig gut metagenome         ┆ s__Bariatricus sp004560705 ┆ pig       │
│ …           ┆ …                          ┆ …                          ┆ …         │
│ SRR16702778 ┆ synthetic metagenome       ┆ s__UBA2868 sp004552595     ┆ unknown   │
│ SRR6811659  ┆ mangrove metagenome        ┆ s__UBA2868 sp004552595     ┆ unknown   │
│ SRR26991454 ┆ estuary metagenome         ┆ s__UBA2868 sp004552595     ┆ unknown   │
│ SRR7648335  ┆ marine sediment metagenome ┆ s__UBA2868 sp004552595     ┆ unknown   │
│ SRR12349269 ┆ aquatic metagenome         ┆ s__UBA2868 sp004552595     ┆ unknown   │
└─────────────┴────────────────────────────┴────────────────────────────┴───────────┘

In [37]:
def make_matrices(df):
    acc_df = df['acc'].unique().to_frame().with_row_index(name='acc_index')
    species_df = df['species'].unique().to_frame().with_row_index(name='species_index')
    org_df = df['simpleorg'].unique().to_frame().with_row_index(name='org_index')

    df = df.join(org_df, on='simpleorg', how='left')
    df = df.join(acc_df, on='acc', how='left')
    df = df.join(species_df, on='species', how='left')

    obs = np.zeros((len(acc_df), len(species_df)))
    target = np.zeros((len(acc_df)))

    for row in df.iter_rows(named=True):
        acc_id = row["acc_index"]
        org_id = row["org_index"]
        species_id = row["species_index"]

        obs[acc_id, species_id] = 1
        target[acc_id] = org_id

    print(f'observations matrix shape is: {obs.shape}')

    return df, obs, target

In [38]:
human_pig_only = bw_df.filter(pl.col("simpleorg") != "unknown")
hp_df, hp_obs, hp_target = make_matrices(human_pig_only)

observations matrix shape is: (135603, 15)

In [14]:
hp_df

shape: (321_795, 7)
┌─────────────┬────────────┬────────────────┬───────────┬───────────┬───────────┬───────────────┐
│ acc         ┆ organism   ┆ species        ┆ simpleorg ┆ org_index ┆ acc_index ┆ species_index │
│ ---         ┆ ---        ┆ ---            ┆ ---       ┆ ---       ┆ ---       ┆ ---           │
│ str         ┆ str        ┆ str            ┆ str       ┆ u32       ┆ u32       ┆ u32           │
╞═════════════╪════════════╪════════════════╪═══════════╪═══════════╪═══════════╪═══════════════╡
│ SRR11185229 ┆ pig gut    ┆ s__Bariatricus ┆ pig       ┆ 0         ┆ 9118      ┆ 12            │
│             ┆ metagenome ┆ sp004560705    ┆           ┆           ┆           ┆               │
│ SRR11185232 ┆ pig gut    ┆ s__Bariatricus ┆ pig       ┆ 0         ┆ 124341    ┆ 12            │
│             ┆ metagenome ┆ sp004560705    ┆           ┆           ┆           ┆               │
│ SRR8960383  ┆ pig gut    ┆ s__Bariatricus ┆ pig       ┆ 0         ┆ 14742     ┆ 12            │
│             ┆ metagenome ┆ sp004560705    ┆           ┆           ┆           ┆               │
│ SRR17241623 ┆ pig gut    ┆ s__Bariatricus ┆ pig       ┆ 0         ┆ 20244     ┆ 12            │
│             ┆ metagenome ┆ sp004560705    ┆           ┆           ┆           ┆               │
│ SRR11185262 ┆ pig gut    ┆ s__Bariatricus ┆ pig       ┆ 0         ┆ 75287     ┆ 12            │
│             ┆ metagenome ┆ sp004560705    ┆           ┆           ┆           ┆               │
│ …           ┆ …          ┆ …              ┆ …         ┆ …         ┆ …         ┆ …             │
│ SRR7182054  ┆ pig gut    ┆ s__UBA2868     ┆ pig       ┆ 0         ┆ 61624     ┆ 0             │
│             ┆ metagenome ┆ sp004552595    ┆           ┆           ┆           ┆               │
│ SRR19906145 ┆ pig        ┆ s__UBA2868     ┆ pig       ┆ 0         ┆ 52368     ┆ 0             │
│             ┆ metagenome ┆ sp004552595    ┆           ┆           ┆           ┆               │
│ SRR7182051  ┆ pig gut    ┆ s__UBA2868     ┆ pig       ┆ 0         ┆ 78842     ┆ 0             │
│             ┆ metagenome ┆ sp004552595    ┆           ┆           ┆           ┆               │
│ SRR5091531  ┆ human gut  ┆ s__UBA2868     ┆ human     ┆ 1         ┆ 64432     ┆ 0             │
│             ┆ metagenome ┆ sp004552595    ┆           ┆           ┆           ┆               │
│ SRR11125839 ┆ pig gut    ┆ s__UBA2868     ┆ pig       ┆ 0         ┆ 71713     ┆ 0             │
│             ┆ metagenome ┆ sp004552595    ┆           ┆           ┆           ┆               │
└─────────────┴────────────┴────────────────┴───────────┴───────────┴───────────┴───────────────┘

## 6-Fold Cross Validation approach

Run 6 different splits of the data; train on 1/6 of the data and test on the other 5/6s of the data, and then repeat that for each of the 6 splits.

In [15]:
kf = StratifiedKFold(n_splits=6)

accuracies = []
i = 1
for train_sub, test_sub in kf.split(hp_obs, hp_target):
    dt = DecisionTreeClassifier(random_state=42)
    tree = dt.fit(hp_obs[train_sub], hp_target[train_sub])
    pred = tree.predict(hp_obs[test_sub])

    accuracy = balanced_accuracy_score(hp_target[test_sub], pred)
    accuracies.append(accuracy)
    print(f"iteration {i}: accuracy {accuracy:.3f}")
    i += 1

print(f"mean accuracy across {i-1} splits: {np.mean(accuracies):.3f}")

iteration 1: accuracy 0.985
iteration 2: accuracy 0.987
iteration 3: accuracy 0.985
iteration 4: accuracy 0.985
iteration 5: accuracy 0.985
iteration 6: accuracy 0.980
mean accuracy across 6 splits: 0.984

## What do we after 6-fold cross validation?

This approach lets us check to see that, in general, the performance of any classifer trained on this data will be pretty good - independent of which set of data we use.

Now, to train the best possible classifier for _future_ use, we will use all the data to train:

In [16]:
dt = DecisionTreeClassifier(random_state=42)
tree = dt.fit(hp_obs, hp_target)
pred = tree.predict(hp_obs)

accuracy = balanced_accuracy_score(hp_target, pred)
print(f"full classifier: accuracy {accuracy:.3f}")

full classifier: accuracy 0.987

## What do we do with the full classifier now??

Now we can go back to the original data - not just the human/pig subset, but the one with unknowns. (Or, potentially, new data sets.)

The only thing we need to be careful about is to encode new observations using the species indexes that match the trained classifier, as well as the organism indexes (0 pig, 1 human). Let's extract those:

In [17]:
species_index_df = hp_df.select(['species_index', 'species']).unique()
species_index_df

shape: (15, 2)
┌───────────────┬─────────────────────────────────┐
│ species_index ┆ species                         │
│ ---           ┆ ---                             │
│ u32           ┆ str                             │
╞═══════════════╪═════════════════════════════════╡
│ 13            ┆ s__Mogibacterium_A kristiansen… │
│ 8             ┆ s__Holdemanella porci           │
│ 0             ┆ s__UBA2868 sp004552595          │
│ 2             ┆ s__Cryptobacteroides sp9005469… │
│ 11            ┆ s__JALFVM01 sp022787145         │
│ …             ┆ …                               │
│ 7             ┆ s__Sodaliphilus sp004557565     │
│ 4             ┆ s__Phascolarctobacterium_A suc… │
│ 6             ┆ s__JAFBIX01 sp021531895         │
│ 9             ┆ s__Roseburia inulinivorans      │
│ 5             ┆ s__Fimisoma sp002320005         │
└───────────────┴─────────────────────────────────┘

In [18]:
org_df = hp_df.select(['org_index', 'simpleorg']).unique()
org_df

shape: (2, 2)
┌───────────┬───────────┐
│ org_index ┆ simpleorg │
│ ---       ┆ ---       │
│ u32       ┆ str       │
╞═══════════╪═══════════╡
│ 0         ┆ pig       │
│ 1         ┆ human     │
└───────────┴───────────┘

Now, let's take some of some of the data we didn't touch from the original bw_df, and encode and classify it:

In [19]:
def make_obs_matrix(df, species_df):
    # need a new access mapping
    acc_df = df['acc'].unique().to_frame().with_row_index(name='acc_index')

    # construct new internal data frame, populate
    df = df.join(acc_df, on='acc', how='left')
    df = df.join(species_df, on='species', how='left')

    obs = np.zeros((len(acc_df), len(species_df)))

    for row in df.iter_rows(named=True):
        acc_id = row["acc_index"]
        species_id = row["species_index"]

        obs[acc_id, species_id] = 1

    print(f'observations matrix shape is: {obs.shape}')

    return df, obs

In [20]:
unknown_only_df = bw_df.filter(pl.col("simpleorg") == "unknown")
unk_df, unk_obs = make_obs_matrix(unknown_only_df, species_index_df)

observations matrix shape is: (74058, 15)

In [21]:
unknown_pred = tree.predict(unk_obs)
unknown_pred

array([0., 1., 1., ..., 1., 1., 1.], shape=(74058,))

## Predictions are great and all but...

Great! XXX predictions 😭 . What do we do with them??

Let's merge the predictions back into the spreadsheet.

In [22]:
unk_pred_df = []
for (row_n, predicted_org) in enumerate(unknown_pred):
    unk_pred_df.append(dict(acc_index=row_n, org_index=int(predicted_org)))
unk_pred_df = pl.DataFrame(unk_pred_df).join(org_df, on='org_index', how='left')

unk_acc_df = unk_df.select(["acc", "acc_index"]).unique()

unk_pred_df = unk_pred_df.join(unk_acc_df, on='acc_index', how='left')
unk_pred_df

shape: (74_058, 4)
┌───────────┬───────────┬───────────┬─────────────┐
│ acc_index ┆ org_index ┆ simpleorg ┆ acc         │
│ ---       ┆ ---       ┆ ---       ┆ ---         │
│ i64       ┆ i64       ┆ str       ┆ str         │
╞═══════════╪═══════════╪═══════════╪═════════════╡
│ 0         ┆ 0         ┆ pig       ┆ SRR8527077  │
│ 1         ┆ 1         ┆ human     ┆ SRR1612046  │
│ 2         ┆ 1         ┆ human     ┆ SRR23593190 │
│ 3         ┆ 0         ┆ pig       ┆ SRR6197822  │
│ 4         ┆ 1         ┆ human     ┆ SRR20217199 │
│ …         ┆ …         ┆ …         ┆ …           │
│ 74053     ┆ 0         ┆ pig       ┆ ERR1543553  │
│ 74054     ┆ 1         ┆ human     ┆ ERR6002083  │
│ 74055     ┆ 1         ┆ human     ┆ SRR18706969 │
│ 74056     ┆ 1         ┆ human     ┆ ERR9690362  │
│ 74057     ┆ 1         ┆ human     ┆ ERR2607570  │
└───────────┴───────────┴───────────┴─────────────┘

In [23]:
unk_pred_df["simpleorg"].value_counts().sort(by='count', descending=True)

shape: (2, 2)
┌───────────┬───────┐
│ simpleorg ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ human     ┆ 66238 │
│ pig       ┆ 7820  │
└───────────┴───────┘

## OK! We have our predictions... did this actually work?

In [24]:
# sample 5 randomly
unk_pred_df.sample(n=5)

shape: (5, 4)
┌───────────┬───────────┬───────────┬─────────────┐
│ acc_index ┆ org_index ┆ simpleorg ┆ acc         │
│ ---       ┆ ---       ┆ ---       ┆ ---         │
│ i64       ┆ i64       ┆ str       ┆ str         │
╞═══════════╪═══════════╪═══════════╪═════════════╡
│ 16273     ┆ 0         ┆ pig       ┆ SRR11482390 │
│ 48198     ┆ 0         ┆ pig       ┆ ERR1726769  │
│ 59289     ┆ 1         ┆ human     ┆ SRR3954466  │
│ 60606     ┆ 1         ┆ human     ┆ SRR11172560 │
│ 20678     ┆ 1         ┆ human     ┆ ERR3097419  │
└───────────┴───────────┴───────────┴─────────────┘

In [25]:
# sample 5 predicted as pig
unk_pred_df.filter(pl.col("simpleorg") == "pig").sample(n=5)

shape: (5, 4)
┌───────────┬───────────┬───────────┬─────────────┐
│ acc_index ┆ org_index ┆ simpleorg ┆ acc         │
│ ---       ┆ ---       ┆ ---       ┆ ---         │
│ i64       ┆ i64       ┆ str       ┆ str         │
╞═══════════╪═══════════╪═══════════╪═════════════╡
│ 24506     ┆ 0         ┆ pig       ┆ SRR15400720 │
│ 12556     ┆ 0         ┆ pig       ┆ SRR8978352  │
│ 69451     ┆ 0         ┆ pig       ┆ ERR1726807  │
│ 1102      ┆ 0         ┆ pig       ┆ SRR28738892 │
│ 49695     ┆ 0         ┆ pig       ┆ SRR25542903 │
└───────────┴───────────┴───────────┴─────────────┘

In [26]:
# sample 5 predicted as human
unk_pred_df.filter(pl.col("simpleorg") == "human").sample(n=5)

shape: (5, 4)
┌───────────┬───────────┬───────────┬─────────────┐
│ acc_index ┆ org_index ┆ simpleorg ┆ acc         │
│ ---       ┆ ---       ┆ ---       ┆ ---         │
│ i64       ┆ i64       ┆ str       ┆ str         │
╞═══════════╪═══════════╪═══════════╪═════════════╡
│ 56576     ┆ 1         ┆ human     ┆ ERR12328265 │
│ 9300      ┆ 1         ┆ human     ┆ ERR3345685  │
│ 5825      ┆ 1         ┆ human     ┆ ERR4319987  │
│ 68373     ┆ 1         ┆ human     ┆ SRR21396292 │
│ 41589     ┆ 1         ┆ human     ┆ SRR27423041 │
└───────────┴───────────┴───────────┴─────────────┘

# What features are most important for good classification?

First, let's get the feature importances.

In [27]:
importances_df = []
for (species_index, importance) in enumerate(tree.feature_importances_):
    d = dict(species_index=species_index, importance=importance)
    importances_df.append(d)

importances_df = pl.DataFrame(importances_df)
importances_df = importances_df.join(species_index_df, on='species_index', how='left')
importances_df = importances_df.sort(by='importance', descending=True)
importances_df

shape: (15, 3)
┌───────────────┬────────────┬─────────────────────────────────┐
│ species_index ┆ importance ┆ species                         │
│ ---           ┆ ---        ┆ ---                             │
│ i64           ┆ f64        ┆ str                             │
╞═══════════════╪════════════╪═════════════════════════════════╡
│ 0             ┆ 0.831027   ┆ s__UBA2868 sp004552595          │
│ 12            ┆ 0.07518    ┆ s__Bariatricus sp004560705      │
│ 6             ┆ 0.02636    ┆ s__JAFBIX01 sp021531895         │
│ 9             ┆ 0.02036    ┆ s__Roseburia inulinivorans      │
│ 7             ┆ 0.019297   ┆ s__Sodaliphilus sp004557565     │
│ …             ┆ …          ┆ …                               │
│ 3             ┆ 0.001605   ┆ s__Prevotella sp000434975       │
│ 8             ┆ 0.001319   ┆ s__Holdemanella porci           │
│ 4             ┆ 0.001288   ┆ s__Phascolarctobacterium_A suc… │
│ 13            ┆ 0.000713   ┆ s__Mogibacterium_A kristiansen… │
│ 11            ┆ 0.00061    ┆ s__JALFVM01 sp022787145         │
└───────────────┴────────────┴─────────────────────────────────┘

Now let's rebuild the classifier after removing each species, and see how well it does...

In [28]:
species_in_order = importances_df['species'].to_list()
species_in_order

['s__UBA2868 sp004552595',
 's__Bariatricus sp004560705',
 's__JAFBIX01 sp021531895',
 's__Roseburia inulinivorans',
 's__Sodaliphilus sp004557565',
 's__Gemmiger qucibialis',
 's__Prevotella sp002251295',
 's__Lactobacillus amylovorus',
 's__Fimisoma sp002320005',
 's__Cryptobacteroides sp900546925',
 's__Prevotella sp000434975',
 's__Holdemanella porci',
 's__Phascolarctobacterium_A succinatutens',
 's__Mogibacterium_A kristiansenii',
 's__JALFVM01 sp022787145']

In [29]:
human_pig_only = bw_df.filter(pl.col("simpleorg") != "unknown")
species_to_rm = list(species_in_order)

remove_df = human_pig_only
while len(species_to_rm) >= 2:
    rm_species = species_to_rm.pop(0)
    print(f'removing {rm_species} too')
    if len(species_to_rm) == 1:
        print('left:', species_to_rm[0])

    remove_df = remove_df.filter(pl.col("species") != rm_species)
    augmented_df, rm_obs, rm_target = make_matrices(remove_df)

    dt = DecisionTreeClassifier(random_state=42)
    tree = dt.fit(rm_obs, rm_target)
    pred = tree.predict(rm_obs)

    accuracy = balanced_accuracy_score(rm_target, pred)
    print(f"classifier accuracy with {remove_df['species'].n_unique()} is: {accuracy:.3f}")
    print('---')

removing s__UBA2868 sp004552595 too
observations matrix shape is: (135524, 14)
classifier accuracy with 14 is: 0.981
---
removing s__Bariatricus sp004560705 too
observations matrix shape is: (135513, 13)
classifier accuracy with 13 is: 0.979
---
removing s__JAFBIX01 sp021531895 too
observations matrix shape is: (135486, 12)
classifier accuracy with 12 is: 0.974
---
removing s__Roseburia inulinivorans too
observations matrix shape is: (114236, 11)
classifier accuracy with 11 is: 0.971
---
removing s__Sodaliphilus sp004557565 too
observations matrix shape is: (113707, 10)
classifier accuracy with 10 is: 0.975
---
removing s__Gemmiger qucibialis too
observations matrix shape is: (30123, 9)
classifier accuracy with 9 is: 0.955
---
removing s__Prevotella sp002251295 too
observations matrix shape is: (29954, 8)
classifier accuracy with 8 is: 0.952
---
removing s__Lactobacillus amylovorus too
observations matrix shape is: (29084, 7)
classifier accuracy with 7 is: 0.941
---
removing s__Fimisoma sp002320005 too
observations matrix shape is: (28453, 6)
classifier accuracy with 6 is: 0.936
---
removing s__Cryptobacteroides sp900546925 too
observations matrix shape is: (28124, 5)
classifier accuracy with 5 is: 0.912
---
removing s__Prevotella sp000434975 too
observations matrix shape is: (20325, 4)
classifier accuracy with 4 is: 0.916
---
removing s__Holdemanella porci too
observations matrix shape is: (19468, 3)
classifier accuracy with 3 is: 0.923
---
removing s__Phascolarctobacterium_A succinatutens too
observations matrix shape is: (13860, 2)
classifier accuracy with 2 is: 0.901
---
removing s__Mogibacterium_A kristiansenii too
left: s__JALFVM01 sp022787145
observations matrix shape is: (5096, 1)
classifier accuracy with 1 is: 0.500
---

## Remove in reverse order...

In [39]:
human_pig_only = bw_df.filter(pl.col("simpleorg") != "unknown")
species_to_rm = list(reversed(species_in_order))

remove_df = human_pig_only
while len(species_to_rm) >= 2:
    remove_df = remove_df.filter(pl.col("species") != rm_species)
    augmented_df, rm_obs, rm_target = make_matrices(remove_df)

    dt = DecisionTreeClassifier(random_state=42)
    tree = dt.fit(rm_obs, rm_target)
    pred = tree.predict(rm_obs)

    accuracy = balanced_accuracy_score(rm_target, pred)
    print(f"classifier accuracy with {remove_df['species'].n_unique()} is: {accuracy:.3f}")
    print('---')

    rm_species = species_to_rm.pop(0)
    print(f'removing {rm_species} too')

observations matrix shape is: (135593, 14)
classifier accuracy with 14 is: 0.985
---
removing s__JALFVM01 sp022787145 too
observations matrix shape is: (135587, 13)
classifier accuracy with 13 is: 0.985
---
removing s__Mogibacterium_A kristiansenii too
observations matrix shape is: (134844, 12)
classifier accuracy with 12 is: 0.984
---
removing s__Phascolarctobacterium_A succinatutens too
observations matrix shape is: (134503, 11)
classifier accuracy with 11 is: 0.983
---
removing s__Holdemanella porci too
observations matrix shape is: (134466, 10)
classifier accuracy with 10 is: 0.983
---
removing s__Prevotella sp000434975 too
observations matrix shape is: (133202, 9)
classifier accuracy with 9 is: 0.984
---
removing s__Cryptobacteroides sp900546925 too
observations matrix shape is: (133159, 8)
classifier accuracy with 8 is: 0.984
---
removing s__Fimisoma sp002320005 too
observations matrix shape is: (133114, 7)
classifier accuracy with 7 is: 0.981
---
removing s__Lactobacillus amylovorus too
observations matrix shape is: (132814, 6)
classifier accuracy with 6 is: 0.979
---
removing s__Prevotella sp002251295 too
observations matrix shape is: (132765, 5)
classifier accuracy with 5 is: 0.963
---
removing s__Gemmiger qucibialis too
observations matrix shape is: (110532, 4)
classifier accuracy with 4 is: 0.961
---
removing s__Sodaliphilus sp004557565 too
observations matrix shape is: (109054, 3)
classifier accuracy with 3 is: 0.989
---
removing s__Roseburia inulinivorans too
observations matrix shape is: (6811, 2)
classifier accuracy with 2 is: 0.500
---
removing s__JAFBIX01 sp021531895 too
observations matrix shape is: (6030, 1)
classifier accuracy with 1 is: 0.500
---
removing s__Bariatricus sp004560705 too