In [1]:
import polars as pl
import glob
import os.path

In [2]:
SCALED=1000
HASH_THRESHOLD=0 # int(20000 / SCALED)
CONTAINMENT_THRESHOLD=0


#CSVPATH=f'../outputs.mapping/cds/singlehash.k21/outputs.3216.min{MIN}/manysearch.3216.csv'
CSVPATH=f'/home/ctbrown/scratch3/2025-workflow-core99/outputs.cds/cds3-genes/manysearch.3216.csv'

In [3]:
CORENAMES = set([ x.strip() for x in open('../inputs.mapping/names.list') ])

In [4]:
dflist = []
#ms_filenames = glob.glob('../manysearch-3216/*.cds.x.3216.manysearch.csv')
ms_filenames = glob.glob(CSVPATH)
for filename in ms_filenames:
    print(os.path.basename(filename))
    df = pl.read_csv(filename)
    dflist.append(df)

df = pl.concat(dflist)

manysearch.3216.csv

In [5]:
df

shape: (13_552, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__Phasco ┆ 1a89fbd85 ┆ SRR111840 ┆ 0.857143  ┆ … ┆ 0.795216  ┆ 0.992686  ┆ 24        ┆ 872938   │
│ larctobac ┆ 86de8774a ┆ 89        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Holdem ┆ 9d7cbff65 ┆ SRR111840 ┆ 1.0       ┆ … ┆ 0.783639  ┆ 1.0       ┆ 10        ┆ 872938   │
│ anella    ┆ f24b0f4d1 ┆ 89        ┆           ┆   ┆           ┆           ┆           ┆          │
│ porci     ┆ 1e0f5ab88 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 4e5…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Mogiba ┆ df2825263 ┆ SRR111840 ┆ 0.714286  ┆ … ┆ 0.788342  ┆ 0.984105  ┆ 70        ┆ 872938   │
│ cterium_A ┆ c4d38115f ┆ 89        ┆           ┆   ┆           ┆           ┆           ┆          │
│ kristians ┆ 3d51ec202 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ en…       ┆ 50c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Lactob ┆ 750b12916 ┆ SRR111840 ┆ 0.833333  ┆ … ┆ 0.791967  ┆ 0.991356  ┆ 158       ┆ 872938   │
│ acillus   ┆ e258ed448 ┆ 89        ┆           ┆   ┆           ┆           ┆           ┆          │
│ amylovoru ┆ fae467a19 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s         ┆ 0c8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 1a89fbd85 ┆ SRR111250 ┆ 0.714286  ┆ … ┆ 0.785747  ┆ 0.984105  ┆ 10        ┆ 926910   │
│ larctobac ┆ 86de8774a ┆ 81        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__Mogiba ┆ df2825263 ┆ SRR172416 ┆ 1.0       ┆ … ┆ 0.768471  ┆ 1.0       ┆ 62        ┆ 26359732 │
│ cterium_A ┆ c4d38115f ┆ 36        ┆           ┆   ┆           ┆           ┆           ┆          │
│ kristians ┆ 3d51ec202 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ en…       ┆ 50c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Lactob ┆ 750b12916 ┆ SRR172416 ┆ 0.833333  ┆ … ┆ 0.759882  ┆ 0.991356  ┆ 472       ┆ 26359732 │
│ acillus   ┆ e258ed448 ┆ 36        ┆           ┆   ┆           ┆           ┆           ┆          │
│ amylovoru ┆ fae467a19 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s         ┆ 0c8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 1a89fbd85 ┆ SRR115513 ┆ 0.142857  ┆ … ┆ 0.702936  ┆ 0.911501  ┆ 1         ┆ 7864067  │
│ larctobac ┆ 86de8774a ┆ 68        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ 4d5149fb1 ┆ SRR115513 ┆ 0.5       ┆ … ┆ 0.744227  ┆ 0.967532  ┆ 9         ┆ 7864067  │
│ ricus sp0 ┆ c269db3d2 ┆ 68        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ caa4e0c8d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ db4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Holdem ┆ 9d7cbff65 ┆ SRR115513 ┆ 0.5       ┆ … ┆ 0.730951  ┆ 0.967532  ┆ 1         ┆ 7864067  │
│ anella    ┆ f24b0f4d1 ┆ 68        ┆           ┆   ┆           ┆           ┆           ┆          │
│ porci     ┆ 1e0f5ab88 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 4e5…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
df.sort(by='intersect_hashes').filter(pl.col("intersect_hashes") < 20)

shape: (13_552, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__Holdem ┆ 9d7cbff65 ┆ SRR111250 ┆ 0.5       ┆ … ┆ 0.755792  ┆ 0.967532  ┆ 1         ┆ 926910   │
│ anella    ┆ f24b0f4d1 ┆ 81        ┆           ┆   ┆           ┆           ┆           ┆          │
│ porci     ┆ 1e0f5ab88 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 4e5…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ 4d5149fb1 ┆ SRR111833 ┆ 0.166667  ┆ … ┆ 0.730908  ┆ 0.918217  ┆ 1         ┆ 1385955  │
│ ricus sp0 ┆ c269db3d2 ┆ 80        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ caa4e0c8d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ db4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ 4d5149fb1 ┆ SRR111251 ┆ 0.166667  ┆ … ┆ 0.73152   ┆ 0.918217  ┆ 16        ┆ 928151   │
│ ricus sp0 ┆ c269db3d2 ┆ 85        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ caa4e0c8d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ db4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ 4d5149fb1 ┆ SRR111834 ┆ 0.166667  ┆ … ┆ 0.729287  ┆ 0.918217  ┆ 1         ┆ 1086477  │
│ ricus sp0 ┆ c269db3d2 ┆ 60        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ caa4e0c8d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ db4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Holdem ┆ 9d7cbff65 ┆ SRR111840 ┆ 0.5       ┆ … ┆ 0.75198   ┆ 0.967532  ┆ 2         ┆ 1116525  │
│ anella    ┆ f24b0f4d1 ┆ 10        ┆           ┆   ┆           ┆           ┆           ┆          │
│ porci     ┆ 1e0f5ab88 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 4e5…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__Phasco ┆ 1a89fbd85 ┆ ERR321192 ┆ 1.0       ┆ … ┆ 0.777659  ┆ 1.0       ┆ 23        ┆ 3973030  │
│ larctobac ┆ 86de8774a ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 1a89fbd85 ┆ ERR321179 ┆ 1.0       ┆ … ┆ 0.780267  ┆ 1.0       ┆ 42        ┆ 2939430  │
│ larctobac ┆ 86de8774a ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 1a89fbd85 ┆ ERR113532 ┆ 1.0       ┆ … ┆ 0.774309  ┆ 1.0       ┆ 71        ┆ 5828393  │
│ larctobac ┆ 86de8774a ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 1a89fbd85 ┆ ERR113535 ┆ 1.0       ┆ … ┆ 0.774685  ┆ 1.0       ┆ 44        ┆ 4902673  │
│ larctobac ┆ 86de8774a ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Mogiba ┆ df2825263 ┆ SRR172416 ┆ 1.0       ┆ … ┆ 0.768471  ┆ 1.0       ┆ 62        ┆ 26359732 │
│ cterium_A ┆ c4d38115f ┆ 36        ┆           ┆   ┆           ┆           ┆           ┆          │
│ kristians ┆ 3d51ec202 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ en…       ┆ 50c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
len(df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD))

13552

In [8]:
for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent', descending=True).iter_rows(named=True):
    name = row['query_name']
    if name in CORENAMES:
        name = '** ' + name
    print(f"{row['percent']:.1f}% {name} ")

93.6% ** s__Bariatricus sp004560705
92.0% ** s__Lactobacillus amylovorus
82.4% ** s__Phascolarctobacterium_A succinatutens
80.6% ** s__Mogibacterium_A kristiansenii
72.8% ** s__Holdemanella porci

In [9]:
for row in df.filter(pl.col("containment") >= CONTAINMENT_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    print(f"{row['percent']:.1f}% {row['query_name']} ")

72.8% s__Holdemanella porci
80.6% s__Mogibacterium_A kristiansenii
82.4% s__Phascolarctobacterium_A succinatutens
92.0% s__Lactobacillus amylovorus
93.6% s__Bariatricus sp004560705

In [10]:
df

shape: (13_552, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__Phasco ┆ 1a89fbd85 ┆ SRR111840 ┆ 0.857143  ┆ … ┆ 0.795216  ┆ 0.992686  ┆ 24        ┆ 872938   │
│ larctobac ┆ 86de8774a ┆ 89        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Holdem ┆ 9d7cbff65 ┆ SRR111840 ┆ 1.0       ┆ … ┆ 0.783639  ┆ 1.0       ┆ 10        ┆ 872938   │
│ anella    ┆ f24b0f4d1 ┆ 89        ┆           ┆   ┆           ┆           ┆           ┆          │
│ porci     ┆ 1e0f5ab88 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 4e5…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Mogiba ┆ df2825263 ┆ SRR111840 ┆ 0.714286  ┆ … ┆ 0.788342  ┆ 0.984105  ┆ 70        ┆ 872938   │
│ cterium_A ┆ c4d38115f ┆ 89        ┆           ┆   ┆           ┆           ┆           ┆          │
│ kristians ┆ 3d51ec202 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ en…       ┆ 50c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Lactob ┆ 750b12916 ┆ SRR111840 ┆ 0.833333  ┆ … ┆ 0.791967  ┆ 0.991356  ┆ 158       ┆ 872938   │
│ acillus   ┆ e258ed448 ┆ 89        ┆           ┆   ┆           ┆           ┆           ┆          │
│ amylovoru ┆ fae467a19 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s         ┆ 0c8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 1a89fbd85 ┆ SRR111250 ┆ 0.714286  ┆ … ┆ 0.785747  ┆ 0.984105  ┆ 10        ┆ 926910   │
│ larctobac ┆ 86de8774a ┆ 81        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__Mogiba ┆ df2825263 ┆ SRR172416 ┆ 1.0       ┆ … ┆ 0.768471  ┆ 1.0       ┆ 62        ┆ 26359732 │
│ cterium_A ┆ c4d38115f ┆ 36        ┆           ┆   ┆           ┆           ┆           ┆          │
│ kristians ┆ 3d51ec202 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ en…       ┆ 50c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Lactob ┆ 750b12916 ┆ SRR172416 ┆ 0.833333  ┆ … ┆ 0.759882  ┆ 0.991356  ┆ 472       ┆ 26359732 │
│ acillus   ┆ e258ed448 ┆ 36        ┆           ┆   ┆           ┆           ┆           ┆          │
│ amylovoru ┆ fae467a19 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s         ┆ 0c8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 1a89fbd85 ┆ SRR115513 ┆ 0.142857  ┆ … ┆ 0.702936  ┆ 0.911501  ┆ 1         ┆ 7864067  │
│ larctobac ┆ 86de8774a ┆ 68        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ 4d5149fb1 ┆ SRR115513 ┆ 0.5       ┆ … ┆ 0.744227  ┆ 0.967532  ┆ 9         ┆ 7864067  │
│ ricus sp0 ┆ c269db3d2 ┆ 68        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ caa4e0c8d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ db4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Holdem ┆ 9d7cbff65 ┆ SRR115513 ┆ 0.5       ┆ … ┆ 0.730951  ┆ 0.967532  ┆ 1         ┆ 7864067  │
│ anella    ┆ f24b0f4d1 ┆ 68        ┆           ┆   ┆           ┆           ┆           ┆          │
│ porci     ┆ 1e0f5ab88 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 4e5…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
SUB_SPECIES2=(
             's__Cryptobacteroides sp900546925',
             's__Phascolarctobacterium_A succinatutens',
             's__Mogibacterium_A kristiansenii',
             's__Prevotella sp002251295',
#             's__Prevotella sp000434975',
#             's__Holdemanella porci',
)

for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    if row["query_name"] in SUB_SPECIES2:
        print(f"{row['percent']:.1f}% {row['query_name']} ")

80.6% s__Mogibacterium_A kristiansenii
82.4% s__Phascolarctobacterium_A succinatutens

In [12]:
for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    print(f"{row['percent']:.1f}% {row['query_name']} ")

72.8% s__Holdemanella porci
80.6% s__Mogibacterium_A kristiansenii
82.4% s__Phascolarctobacterium_A succinatutens
92.0% s__Lactobacillus amylovorus
93.6% s__Bariatricus sp004560705