In [1]:
import polars as pl
import glob
import os.path

In [2]:
MIN=90
SCALED=1000
HASH_THRESHOLD=int(20000 / SCALED)

#CSVPATH=f'../outputs.mapping/cds/singlehash.k21/outputs.3216.min{MIN}/manysearch.3216.csv'
CSVPATH=f'/Users/t/dev/2025-workflow-core99/outputs.mapping/cds2/manysearch.3216.parquet'

In [3]:
dflist = []
#ms_filenames = glob.glob('../manysearch-3216/*.cds.x.3216.manysearch.csv')
ms_filenames = glob.glob(CSVPATH)
for filename in ms_filenames:
    print(os.path.basename(filename))
    df = pl.read_parquet(filename)
    dflist.append(df)

df = pl.concat(dflist)

manysearch.3216.parquet

In [4]:
df

shape: (48_146, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__Phasco ┆ 6faeda743 ┆ SRR111840 ┆ 0.377049  ┆ … ┆ 0.814555  ┆ 0.954615  ┆ 561       ┆ 1062544  │
│ larctobac ┆ d83459fe9 ┆ 44        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ f84333d39 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 763…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Holdem ┆ 04d29ac49 ┆ SRR111840 ┆ 0.461538  ┆ … ┆ 0.782145  ┆ 0.963851  ┆ 71        ┆ 1062544  │
│ anella    ┆ a344664c7 ┆ 44        ┆           ┆   ┆           ┆           ┆           ┆          │
│ porci     ┆ bcbe38ff9 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ c1c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__UBA286 ┆ 4d940c2e2 ┆ SRR111840 ┆ 0.526316  ┆ … ┆ 0.79256   ┆ 0.969898  ┆ 108       ┆ 1062544  │
│ 8 sp00455 ┆ 2dd12ab70 ┆ 44        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2595      ┆ 7e41ef9ab ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 511…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Prevot ┆ fe26f0e86 ┆ SRR111840 ┆ 0.523179  ┆ … ┆ 0.824238  ┆ 0.969622  ┆ 903       ┆ 1062544  │
│ ella sp00 ┆ 3bf2aee45 ┆ 44        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0434975   ┆ 32f13bedf ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ec1…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Fimiso ┆ 2c2a7b639 ┆ SRR111840 ┆ 0.769231  ┆ … ┆ 0.811726  ┆ 0.987584  ┆ 276       ┆ 1062544  │
│ ma sp0023 ┆ 2862780b9 ┆ 44        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 20005     ┆ 2210a1c66 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ abe…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__Bariat ┆ e9a46feeb ┆ ERR831477 ┆ 0.9       ┆ … ┆ 0.785017  ┆ 0.994995  ┆ 641       ┆ 11853922 │
│ ricus sp0 ┆ 7d267e94c ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ dc5169605 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 5af…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Gemmig ┆ e186a824f ┆ ERR831477 ┆ 0.66763   ┆ … ┆ 0.808936  ┆ 0.980945  ┆ 7240      ┆ 11853922 │
│ er qucibi ┆ 62d426f10 ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ alis      ┆ 81cc1e41a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 69e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Sodali ┆ d62cacba6 ┆ ERR831477 ┆ 0.499701  ┆ … ┆ 0.822311  ┆ 0.967504  ┆ 23262     ┆ 11853922 │
│ philus    ┆ a82e86ba2 ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp0045575 ┆ 718cf2420 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 65        ┆ 8e1…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__JAFBIX ┆ 708951a33 ┆ ERR831477 ┆ 0.818182  ┆ … ┆ 0.777266  ┆ 0.99049   ┆ 221       ┆ 11853922 │
│ 01 sp0215 ┆ ed125f97d ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 31895     ┆ 874c9a15d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0cb…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Crypto ┆ d52453453 ┆ ERR831477 ┆ 0.852273  ┆ … ┆ 0.798061  ┆ 0.992417  ┆ 4180      ┆ 11853922 │
│ bacteroid ┆ 711610315 ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ es sp9005 ┆ 9223dafc8 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 469…      ┆ 701…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
df.sort(by='intersect_hashes').filter(pl.col("intersect_hashes") < 20)

shape: (11_746, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__Phasco ┆ 6faeda743 ┆ ERR321202 ┆ 0.005464  ┆ … ┆ 0.676614  ┆ 0.780305  ┆ 4         ┆ 1580518  │
│ larctobac ┆ d83459fe9 ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ f84333d39 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 763…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Mogiba ┆ 757c78b0d ┆ ERR321202 ┆ 0.007752  ┆ … ┆ 0.683164  ┆ 0.793406  ┆ 71        ┆ 1580518  │
│ cterium_A ┆ c56f0dc3d ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ kristians ┆ fdfa384e1 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ en…       ┆ 8fd…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Gemmig ┆ e186a824f ┆ ERR321202 ┆ 0.00289   ┆ … ┆ 0.664958  ┆ 0.756993  ┆ 3         ┆ 1580518  │
│ er qucibi ┆ 62d426f10 ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ alis      ┆ 81cc1e41a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 69e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Sodali ┆ d62cacba6 ┆ ERR321202 ┆ 0.000598  ┆ … ┆ 0.637613  ┆ 0.702304  ┆ 1         ┆ 1580518  │
│ philus    ┆ a82e86ba2 ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp0045575 ┆ 718cf2420 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 65        ┆ 8e1…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Holdem ┆ 04d29ac49 ┆ SRR524074 ┆ 0.076923  ┆ … ┆ 0.708833  ┆ 0.885024  ┆ 4         ┆ 3554248  │
│ anella    ┆ a344664c7 ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│ porci     ┆ bcbe38ff9 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ c1c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__UBA286 ┆ 4d940c2e2 ┆ SRR172416 ┆ 1.0       ┆ … ┆ 0.790339  ┆ 1.0       ┆ 1240      ┆ 15223972 │
│ 8 sp00455 ┆ 2dd12ab70 ┆ 30        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2595      ┆ 7e41ef9ab ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 511…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__UBA286 ┆ 4d940c2e2 ┆ SRR172416 ┆ 1.0       ┆ … ┆ 0.786836  ┆ 1.0       ┆ 1404      ┆ 15749433 │
│ 8 sp00455 ┆ 2dd12ab70 ┆ 00        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2595      ┆ 7e41ef9ab ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 511…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__JAFBIX ┆ 708951a33 ┆ SRR172416 ┆ 0.863636  ┆ … ┆ 0.783358  ┆ 0.993043  ┆ 504       ┆ 15749433 │
│ 01 sp0215 ┆ ed125f97d ┆ 00        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 31895     ┆ 874c9a15d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0cb…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__UBA286 ┆ 4d940c2e2 ┆ ERR831477 ┆ 1.0       ┆ … ┆ 0.783246  ┆ 1.0       ┆ 475       ┆ 11563988 │
│ 8 sp00455 ┆ 2dd12ab70 ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2595      ┆ 7e41ef9ab ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 511…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__UBA286 ┆ 4d940c2e2 ┆ ERR831477 ┆ 1.0       ┆ … ┆ 0.782748  ┆ 1.0       ┆ 481       ┆ 11853922 │
│ 8 sp00455 ┆ 2dd12ab70 ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2595      ┆ 7e41ef9ab ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 511…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
len(df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD))

36400

In [7]:
for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    print(f"{row['percent']:.1f}% {row['query_name']} ")

5.1% s__JAFBIX01 sp021531895
66.6% s__Bariatricus sp004560705
85.1% s__Fimisoma sp002320005
89.7% s__Roseburia inulinivorans
94.2% s__Prevotella sp002251295
97.6% s__Cryptobacteroides sp900546925
98.2% s__Phascolarctobacterium_A succinatutens
99.0% s__JALFVM01 sp022787145
99.1% s__Sodaliphilus sp004557565
99.1% s__Prevotella sp000434975
99.3% s__Gemmiger qucibialis
99.3% s__Mogibacterium_A kristiansenii
99.3% s__Lactobacillus amylovorus

In [8]:
df

shape: (48_146, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__Phasco ┆ 6faeda743 ┆ SRR111840 ┆ 0.377049  ┆ … ┆ 0.814555  ┆ 0.954615  ┆ 561       ┆ 1062544  │
│ larctobac ┆ d83459fe9 ┆ 44        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ f84333d39 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 763…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Holdem ┆ 04d29ac49 ┆ SRR111840 ┆ 0.461538  ┆ … ┆ 0.782145  ┆ 0.963851  ┆ 71        ┆ 1062544  │
│ anella    ┆ a344664c7 ┆ 44        ┆           ┆   ┆           ┆           ┆           ┆          │
│ porci     ┆ bcbe38ff9 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ c1c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__UBA286 ┆ 4d940c2e2 ┆ SRR111840 ┆ 0.526316  ┆ … ┆ 0.79256   ┆ 0.969898  ┆ 108       ┆ 1062544  │
│ 8 sp00455 ┆ 2dd12ab70 ┆ 44        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2595      ┆ 7e41ef9ab ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 511…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Prevot ┆ fe26f0e86 ┆ SRR111840 ┆ 0.523179  ┆ … ┆ 0.824238  ┆ 0.969622  ┆ 903       ┆ 1062544  │
│ ella sp00 ┆ 3bf2aee45 ┆ 44        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0434975   ┆ 32f13bedf ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ec1…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Fimiso ┆ 2c2a7b639 ┆ SRR111840 ┆ 0.769231  ┆ … ┆ 0.811726  ┆ 0.987584  ┆ 276       ┆ 1062544  │
│ ma sp0023 ┆ 2862780b9 ┆ 44        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 20005     ┆ 2210a1c66 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ abe…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__Bariat ┆ e9a46feeb ┆ ERR831477 ┆ 0.9       ┆ … ┆ 0.785017  ┆ 0.994995  ┆ 641       ┆ 11853922 │
│ ricus sp0 ┆ 7d267e94c ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ dc5169605 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 5af…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Gemmig ┆ e186a824f ┆ ERR831477 ┆ 0.66763   ┆ … ┆ 0.808936  ┆ 0.980945  ┆ 7240      ┆ 11853922 │
│ er qucibi ┆ 62d426f10 ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ alis      ┆ 81cc1e41a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 69e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Sodali ┆ d62cacba6 ┆ ERR831477 ┆ 0.499701  ┆ … ┆ 0.822311  ┆ 0.967504  ┆ 23262     ┆ 11853922 │
│ philus    ┆ a82e86ba2 ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp0045575 ┆ 718cf2420 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 65        ┆ 8e1…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__JAFBIX ┆ 708951a33 ┆ ERR831477 ┆ 0.818182  ┆ … ┆ 0.777266  ┆ 0.99049   ┆ 221       ┆ 11853922 │
│ 01 sp0215 ┆ ed125f97d ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 31895     ┆ 874c9a15d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0cb…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Crypto ┆ d52453453 ┆ ERR831477 ┆ 0.852273  ┆ … ┆ 0.798061  ┆ 0.992417  ┆ 4180      ┆ 11853922 │
│ bacteroid ┆ 711610315 ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ es sp9005 ┆ 9223dafc8 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 469…      ┆ 701…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
SUB_SPECIES2=(
             's__Cryptobacteroides sp900546925',
             's__Phascolarctobacterium_A succinatutens',
             's__Mogibacterium_A kristiansenii',
             's__Prevotella sp002251295',
#             's__Prevotella sp000434975',
#             's__Holdemanella porci',
)

for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    if row["query_name"] in SUB_SPECIES2:
        print(f"{row['percent']:.1f}% {row['query_name']} ")

94.2% s__Prevotella sp002251295
97.6% s__Cryptobacteroides sp900546925
98.2% s__Phascolarctobacterium_A succinatutens
99.3% s__Mogibacterium_A kristiansenii

In [10]:
for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    print(f"{row['percent']:.1f}% {row['query_name']} ")

5.1% s__JAFBIX01 sp021531895
66.6% s__Bariatricus sp004560705
85.1% s__Fimisoma sp002320005
89.7% s__Roseburia inulinivorans
94.2% s__Prevotella sp002251295
97.6% s__Cryptobacteroides sp900546925
98.2% s__Phascolarctobacterium_A succinatutens
99.0% s__JALFVM01 sp022787145
99.1% s__Sodaliphilus sp004557565
99.1% s__Prevotella sp000434975
99.3% s__Gemmiger qucibialis
99.3% s__Mogibacterium_A kristiansenii
99.3% s__Lactobacillus amylovorus