In [1]:
import polars as pl
import glob
import os.path

In [2]:
SCALED=1000
HASH_THRESHOLD=int(20000 / SCALED)


#CSVPATH=f'../outputs.mapping/cds/singlehash.k21/outputs.3216.min{MIN}/manysearch.3216.csv'
CSVPATH=f'/home/ctbrown/scratch3/2025-workflow-core99/outputs.cds/cds3/manysearch.cds3.3216.csv'

In [3]:
dflist = []
#ms_filenames = glob.glob('../manysearch-3216/*.cds.x.3216.manysearch.csv')
ms_filenames = glob.glob(CSVPATH)
for filename in ms_filenames:
    print(os.path.basename(filename))
    df = pl.read_csv(filename)
    dflist.append(df)

df = pl.concat(dflist)
df

manysearch.cds3.3216.csv

shape: (79_366, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ n_weighte ┆ total_wei ┆ containme ┆ f_weight │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ d_found   ┆ ghted_has ┆ nt_target ┆ ed_targe │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ hes       ┆ _in_query ┆ t_in_que │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ i64       ┆ ---       ┆ ---       ┆ ry       │
│           ┆           ┆           ┆           ┆   ┆           ┆ i64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__SIG351 ┆ deae0769a ┆ SRR111251 ┆ 0.003187  ┆ … ┆ 7         ┆ 1086257   ┆ 0.00002   ┆ 0.000006 │
│ sp9459187 ┆ 7f1129574 ┆ 29        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 95        ┆ 65b790cea ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ca8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Gemmig ┆ fd650d4fb ┆ SRR111251 ┆ 0.000316  ┆ … ┆ 3         ┆ 1086257   ┆ 0.000008  ┆ 0.000003 │
│ er qucibi ┆ 7d4238d62 ┆ 29        ┆           ┆   ┆           ┆           ┆           ┆          │
│ alis      ┆ 70bb07869 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 828…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__JALFVM ┆ 6e456de50 ┆ SRR111251 ┆ 0.00071   ┆ … ┆ 2         ┆ 1086257   ┆ 0.000008  ┆ 0.000002 │
│ 01 sp0227 ┆ 4903038c2 ┆ 29        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 87145     ┆ 51145eeed ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 987…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Lactob ┆ 126daabd3 ┆ SRR111251 ┆ 0.00226   ┆ … ┆ 32        ┆ 1086257   ┆ 0.000036  ┆ 0.000029 │
│ acillus   ┆ e4858fd7f ┆ 29        ┆           ┆   ┆           ┆           ┆           ┆          │
│ amylovoru ┆ 57ebee5c0 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s         ┆ 7f5…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Prevot ┆ 11c2f06bb ┆ SRR111251 ┆ 0.012179  ┆ … ┆ 80        ┆ 1086257   ┆ 0.000252  ┆ 0.000074 │
│ ella sp00 ┆ 0ba002567 ┆ 29        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2251295   ┆ a1bdc2a57 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 126…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__Phasco ┆ 8c3d1fa61 ┆ ERR113528 ┆ 0.007236  ┆ … ┆ 44        ┆ 5889162   ┆ 0.000016  ┆ 0.000007 │
│ larctobac ┆ d73093ded ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 0c14d4577 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 909…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Holdem ┆ 398766a16 ┆ ERR113528 ┆ 0.091565  ┆ … ┆ 315       ┆ 5889162   ┆ 0.000064  ┆ 0.000053 │
│ anella    ┆ d18d486ff ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ porci     ┆ 57f019d26 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 4e4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ a053514b9 ┆ ERR113528 ┆ 0.292683  ┆ … ┆ 2311      ┆ 5889162   ┆ 0.000444  ┆ 0.000392 │
│ ricus sp0 ┆ 87f8c11e2 ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ ed518938e ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 366…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Crypto ┆ 80c1ce43c ┆ ERR113528 ┆ 0.231321  ┆ … ┆ 4568      ┆ 5889162   ┆ 0.000646  ┆ 0.000776 │
│ bacteroid ┆ 8dff68ff8 ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ es sp9005 ┆ ec3e45dae ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 469…      ┆ 136…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Sodali ┆ 01b84a101 ┆ ERR113528 ┆ 0.240875  ┆ … ┆ 35495     ┆ 5889162   ┆ 0.001301  ┆ 0.006027 │
│ philus    ┆ 775aec06b ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp0045575 ┆ 80aef75f7 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 65        ┆ a9b…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
df['query_name'].unique()

shape: (26,)
Series: 'query_name' [str]
[
	"s__Blautia_A sp945872375"
	"s__Cryptobacteroides sp9005469…
	"s__Roseburia inulinivorans"
	"s__CAG-465 sp000433755"
	"s__Prevotella sp000434975"
	…
	"s__UMGS1225 sp034086705"
	"s__Prevotella sp002251295"
	"s__Holdemanella porci"
	"s__SIG351 sp945918795"
	"s__Mogibacterium_A kristiansen…
]

## Summarize by percent across samples.

In [5]:
for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent', descending=True).iter_rows(named=True):
    print(f"{row['percent']:.1f}% {row['query_name']} ")

99.0% s__Sodaliphilus sp004557565
98.5% s__Lactobacillus amylovorus
97.5% s__Cryptobacteroides sp900546925
97.1% s__Fimisoma sp002320005
97.0% s__Mogibacterium_A kristiansenii
96.7% s__UBA2868 sp004552595
96.4% s__Prevotella sp002251295
96.3% s__JAFBIX01 sp021531895
95.7% s__Bariatricus sp004560705
93.8% s__Prevotella sp000434975
90.6% s__JALFVM01 sp022787145
90.1% s__Holdemanella porci
87.6% s__Phascolarctobacterium_A succinatutens
82.7% s__Gemmiger qucibialis
77.6% s__UMGS1225 sp034086705
77.1% s__Roseburia inulinivorans
57.2% s__Ruminococcus_C sp000433635
52.1% s__SIG351 sp945918795
46.6% s__Bifidobacterium thermacidophilum
34.5% s__Blautia_A sp945872375
34.3% s__Ventricola sp017937505
34.1% s__CAG-873 sp016302215
28.8% s__CAG-269 sp014846485
22.4% s__Phascolarctobacterium_A succinatutens_B
20.6% s__CAG-465 sp000433755
19.6% s__Ruminococcoides sp902766885

In [6]:
SUB_SPECIES2=(
             's__Cryptobacteroides sp900546925',
             's__Phascolarctobacterium_A succinatutens',
             's__Mogibacterium_A kristiansenii',
             's__Prevotella sp002251295',
#             's__Prevotella sp000434975',
#             's__Holdemanella porci',
)

for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    if row["query_name"] in SUB_SPECIES2:
        print(f"{row['percent']:.1f}% {row['query_name']} ")

87.6% s__Phascolarctobacterium_A succinatutens
96.4% s__Prevotella sp002251295
97.0% s__Mogibacterium_A kristiansenii
97.5% s__Cryptobacteroides sp900546925

In [7]:
for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    print(f"{row['percent']:.1f}% {row['query_name']} ")

19.6% s__Ruminococcoides sp902766885
20.6% s__CAG-465 sp000433755
22.4% s__Phascolarctobacterium_A succinatutens_B
28.8% s__CAG-269 sp014846485
34.1% s__CAG-873 sp016302215
34.3% s__Ventricola sp017937505
34.5% s__Blautia_A sp945872375
46.6% s__Bifidobacterium thermacidophilum
52.1% s__SIG351 sp945918795
57.2% s__Ruminococcus_C sp000433635
77.1% s__Roseburia inulinivorans
77.6% s__UMGS1225 sp034086705
82.7% s__Gemmiger qucibialis
87.6% s__Phascolarctobacterium_A succinatutens
90.1% s__Holdemanella porci
90.6% s__JALFVM01 sp022787145
93.8% s__Prevotella sp000434975
95.7% s__Bariatricus sp004560705
96.3% s__JAFBIX01 sp021531895
96.4% s__Prevotella sp002251295
96.7% s__UBA2868 sp004552595
97.0% s__Mogibacterium_A kristiansenii
97.1% s__Fimisoma sp002320005
97.5% s__Cryptobacteroides sp900546925
98.5% s__Lactobacillus amylovorus
99.0% s__Sodaliphilus sp004557565