In [1]:
import polars as pl
import glob
import os.path

In [13]:
SCALED=1000
HASH_THRESHOLD=0 # int(20000 / SCALED)
#CONTAINMENT_THRESHOLD=0.01


#CSVPATH=f'../outputs.mapping/cds/singlehash.k21/outputs.3216.min{MIN}/manysearch.3216.csv'
CSVPATH=f'/home/ctbrown/scratch3/2025-workflow-core99/outputs.cds/cds3-genes/manysearch.3216.csv'

In [14]:
CORENAMES = set([ x.strip() for x in open('../inputs.mapping/names.list') ])

In [15]:
dflist = []
#ms_filenames = glob.glob('../manysearch-3216/*.cds.x.3216.manysearch.csv')
ms_filenames = glob.glob(CSVPATH)
for filename in ms_filenames:
    print(os.path.basename(filename))
    df = pl.read_csv(filename)
    dflist.append(df)

df = pl.concat(dflist)

manysearch.3216.csv

In [16]:
df

shape: (8_619, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__Phasco ┆ 1a89fbd85 ┆ SRR111249 ┆ 0.857143  ┆ … ┆ 0.79394   ┆ 0.992686  ┆ 18        ┆ 1073290  │
│ larctobac ┆ 86de8774a ┆ 55        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Lactob ┆ 750b12916 ┆ SRR111249 ┆ 0.833333  ┆ … ┆ 0.790702  ┆ 0.991356  ┆ 555       ┆ 1073290  │
│ acillus   ┆ e258ed448 ┆ 55        ┆           ┆   ┆           ┆           ┆           ┆          │
│ amylovoru ┆ fae467a19 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s         ┆ 0c8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ 4d5149fb1 ┆ SRR111249 ┆ 0.166667  ┆ … ┆ 0.732367  ┆ 0.918217  ┆ 1         ┆ 1073290  │
│ ricus sp0 ┆ c269db3d2 ┆ 55        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ caa4e0c8d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ db4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 1a89fbd85 ┆ SRR111247 ┆ 0.857143  ┆ … ┆ 0.793225  ┆ 0.992686  ┆ 66        ┆ 966057   │
│ larctobac ┆ 86de8774a ┆ 67        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Lactob ┆ 750b12916 ┆ SRR111247 ┆ 0.833333  ┆ … ┆ 0.789993  ┆ 0.991356  ┆ 183       ┆ 966057   │
│ acillus   ┆ e258ed448 ┆ 67        ┆           ┆   ┆           ┆           ┆           ┆          │
│ amylovoru ┆ fae467a19 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s         ┆ 0c8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__Lactob ┆ 750b12916 ┆ SRR172415 ┆ 0.833333  ┆ … ┆ 0.7725    ┆ 0.991356  ┆ 17        ┆ 13247166 │
│ acillus   ┆ e258ed448 ┆ 16        ┆           ┆   ┆           ┆           ┆           ┆          │
│ amylovoru ┆ fae467a19 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s         ┆ 0c8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ 4d5149fb1 ┆ SRR172415 ┆ 0.333333  ┆ … ┆ 0.739519  ┆ 0.94903   ┆ 23        ┆ 13247166 │
│ ricus sp0 ┆ c269db3d2 ┆ 16        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ caa4e0c8d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ db4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 1a89fbd85 ┆ SRR172415 ┆ 0.857143  ┆ … ┆ 0.767004  ┆ 0.992686  ┆ 87        ┆ 14100121 │
│ larctobac ┆ 86de8774a ┆ 37        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Lactob ┆ 750b12916 ┆ SRR172415 ┆ 0.833333  ┆ … ┆ 0.763999  ┆ 0.991356  ┆ 593       ┆ 14100121 │
│ acillus   ┆ e258ed448 ┆ 37        ┆           ┆   ┆           ┆           ┆           ┆          │
│ amylovoru ┆ fae467a19 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s         ┆ 0c8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ 4d5149fb1 ┆ SRR172415 ┆ 1.0       ┆ … ┆ 0.770661  ┆ 1.0       ┆ 48        ┆ 14100121 │
│ ricus sp0 ┆ c269db3d2 ┆ 37        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ caa4e0c8d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ db4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [17]:
df.sort(by='intersect_hashes').filter(pl.col("intersect_hashes") < 20)

shape: (8_619, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__Bariat ┆ 4d5149fb1 ┆ SRR111249 ┆ 0.166667  ┆ … ┆ 0.732367  ┆ 0.918217  ┆ 1         ┆ 1073290  │
│ ricus sp0 ┆ c269db3d2 ┆ 55        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ caa4e0c8d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ db4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ 4d5149fb1 ┆ SRR111255 ┆ 0.166667  ┆ … ┆ 0.729049  ┆ 0.918217  ┆ 1         ┆ 952094   │
│ ricus sp0 ┆ c269db3d2 ┆ 42        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ caa4e0c8d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ db4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Lactob ┆ 750b12916 ┆ SRR111835 ┆ 0.166667  ┆ … ┆ 0.733762  ┆ 0.918217  ┆ 1         ┆ 1299063  │
│ acillus   ┆ e258ed448 ┆ 54        ┆           ┆   ┆           ┆           ┆           ┆          │
│ amylovoru ┆ fae467a19 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s         ┆ 0c8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ 4d5149fb1 ┆ SRR718203 ┆ 0.166667  ┆ … ┆ 0.725341  ┆ 0.918217  ┆ 3         ┆ 1873462  │
│ ricus sp0 ┆ c269db3d2 ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ caa4e0c8d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ db4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ 4d5149fb1 ┆ SRR111259 ┆ 0.166667  ┆ … ┆ 0.738686  ┆ 0.918217  ┆ 1         ┆ 1116858  │
│ ricus sp0 ┆ c269db3d2 ┆ 52        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ caa4e0c8d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ db4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__Phasco ┆ 1a89fbd85 ┆ SRR114897 ┆ 1.0       ┆ … ┆ 0.773615  ┆ 1.0       ┆ 278       ┆ 13503193 │
│ larctobac ┆ 86de8774a ┆ 48        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 1a89fbd85 ┆ ERR321191 ┆ 1.0       ┆ … ┆ 0.780141  ┆ 1.0       ┆ 23        ┆ 3084275  │
│ larctobac ┆ 86de8774a ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 1a89fbd85 ┆ ERR113528 ┆ 1.0       ┆ … ┆ 0.774907  ┆ 1.0       ┆ 38        ┆ 5889162  │
│ larctobac ┆ 86de8774a ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 1a89fbd85 ┆ SRR896088 ┆ 1.0       ┆ … ┆ 0.779437  ┆ 1.0       ┆ 365       ┆ 6078263  │
│ larctobac ┆ 86de8774a ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 1a89fbd85 ┆ ERR831473 ┆ 1.0       ┆ … ┆ 0.773313  ┆ 1.0       ┆ 124       ┆ 9997516  │
│ larctobac ┆ 86de8774a ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [18]:
len(df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD))

8619

In [19]:
for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent', descending=True).iter_rows(named=True):
    name = row['query_name']
    if name in CORENAMES:
        name = '** ' + name
    print(f"{row['percent']:.1f}% {name} ")

93.6% ** s__Bariatricus sp004560705
92.0% ** s__Lactobacillus amylovorus
82.4% ** s__Phascolarctobacterium_A succinatutens

In [20]:
for row in df.filter(pl.col("containment") >= CONTAINMENT_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    print(f"{row['percent']:.1f}% {row['query_name']} ")

82.4% s__Phascolarctobacterium_A succinatutens
92.0% s__Lactobacillus amylovorus
93.6% s__Bariatricus sp004560705

In [21]:
df

shape: (8_619, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__Phasco ┆ 1a89fbd85 ┆ SRR111249 ┆ 0.857143  ┆ … ┆ 0.79394   ┆ 0.992686  ┆ 18        ┆ 1073290  │
│ larctobac ┆ 86de8774a ┆ 55        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Lactob ┆ 750b12916 ┆ SRR111249 ┆ 0.833333  ┆ … ┆ 0.790702  ┆ 0.991356  ┆ 555       ┆ 1073290  │
│ acillus   ┆ e258ed448 ┆ 55        ┆           ┆   ┆           ┆           ┆           ┆          │
│ amylovoru ┆ fae467a19 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s         ┆ 0c8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ 4d5149fb1 ┆ SRR111249 ┆ 0.166667  ┆ … ┆ 0.732367  ┆ 0.918217  ┆ 1         ┆ 1073290  │
│ ricus sp0 ┆ c269db3d2 ┆ 55        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ caa4e0c8d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ db4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 1a89fbd85 ┆ SRR111247 ┆ 0.857143  ┆ … ┆ 0.793225  ┆ 0.992686  ┆ 66        ┆ 966057   │
│ larctobac ┆ 86de8774a ┆ 67        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Lactob ┆ 750b12916 ┆ SRR111247 ┆ 0.833333  ┆ … ┆ 0.789993  ┆ 0.991356  ┆ 183       ┆ 966057   │
│ acillus   ┆ e258ed448 ┆ 67        ┆           ┆   ┆           ┆           ┆           ┆          │
│ amylovoru ┆ fae467a19 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s         ┆ 0c8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__Lactob ┆ 750b12916 ┆ SRR172415 ┆ 0.833333  ┆ … ┆ 0.7725    ┆ 0.991356  ┆ 17        ┆ 13247166 │
│ acillus   ┆ e258ed448 ┆ 16        ┆           ┆   ┆           ┆           ┆           ┆          │
│ amylovoru ┆ fae467a19 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s         ┆ 0c8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ 4d5149fb1 ┆ SRR172415 ┆ 0.333333  ┆ … ┆ 0.739519  ┆ 0.94903   ┆ 23        ┆ 13247166 │
│ ricus sp0 ┆ c269db3d2 ┆ 16        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ caa4e0c8d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ db4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 1a89fbd85 ┆ SRR172415 ┆ 0.857143  ┆ … ┆ 0.767004  ┆ 0.992686  ┆ 87        ┆ 14100121 │
│ larctobac ┆ 86de8774a ┆ 37        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Lactob ┆ 750b12916 ┆ SRR172415 ┆ 0.833333  ┆ … ┆ 0.763999  ┆ 0.991356  ┆ 593       ┆ 14100121 │
│ acillus   ┆ e258ed448 ┆ 37        ┆           ┆   ┆           ┆           ┆           ┆          │
│ amylovoru ┆ fae467a19 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s         ┆ 0c8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ 4d5149fb1 ┆ SRR172415 ┆ 1.0       ┆ … ┆ 0.770661  ┆ 1.0       ┆ 48        ┆ 14100121 │
│ ricus sp0 ┆ c269db3d2 ┆ 37        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ caa4e0c8d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ db4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [22]:
SUB_SPECIES2=(
             's__Cryptobacteroides sp900546925',
             's__Phascolarctobacterium_A succinatutens',
             's__Mogibacterium_A kristiansenii',
             's__Prevotella sp002251295',
#             's__Prevotella sp000434975',
#             's__Holdemanella porci',
)

for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    if row["query_name"] in SUB_SPECIES2:
        print(f"{row['percent']:.1f}% {row['query_name']} ")

82.4% s__Phascolarctobacterium_A succinatutens

In [23]:
for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    print(f"{row['percent']:.1f}% {row['query_name']} ")

82.4% s__Phascolarctobacterium_A succinatutens
92.0% s__Lactobacillus amylovorus
93.6% s__Bariatricus sp004560705