In [1]:
import polars as pl
import glob
import os.path

In [2]:
SCALED=1000
HASH_THRESHOLD=0 # int(20000 / SCALED)
CONTAINMENT_THRESHOLD=0


#CSVPATH=f'../outputs.mapping/cds/singlehash.k21/outputs.3216.min{MIN}/manysearch.3216.csv'
CSVPATH=f'/home/ctbrown/scratch3/2025-workflow-core99/outputs.cds/cds3-genes/manysearch.3216.csv'

In [3]:
CORENAMES = set([ x.strip() for x in open('../inputs.mapping/names.list') ])

In [4]:
dflist = []
#ms_filenames = glob.glob('../manysearch-3216/*.cds.x.3216.manysearch.csv')
ms_filenames = glob.glob(CSVPATH)
for filename in ms_filenames:
    print(os.path.basename(filename))
    df = pl.read_csv(filename)
    dflist.append(df)

df = pl.concat(dflist)

manysearch.3216.csv

In [5]:
df

shape: (26_562, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__Sodali ┆ 73ffbc37a ┆ SRR111835 ┆ 0.857143  ┆ … ┆ 0.79599   ┆ 0.992686  ┆ 110       ┆ 999956   │
│ philus    ┆ dc473b43d ┆ 52        ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp0045575 ┆ 7588f0c7c ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 65        ┆ 591…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Prevot ┆ 46b9539c3 ┆ SRR111835 ┆ 0.125     ┆ … ┆ 0.728002  ┆ 0.905724  ┆ 1         ┆ 999956   │
│ ella sp00 ┆ 30b333990 ┆ 52        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2251295   ┆ 7e4eb0b5c ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 24b…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Crypto ┆ add3c2f0c ┆ SRR111835 ┆ 0.166667  ┆ … ┆ 0.734249  ┆ 0.918217  ┆ 2         ┆ 999956   │
│ bacteroid ┆ 370bea894 ┆ 52        ┆           ┆   ┆           ┆           ┆           ┆          │
│ es sp9005 ┆ a79ff0921 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 469…      ┆ 9bf…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Mogiba ┆ df2825263 ┆ SRR111835 ┆ 0.857143  ┆ … ┆ 0.79599   ┆ 0.992686  ┆ 29        ┆ 999956   │
│ cterium_A ┆ c4d38115f ┆ 52        ┆           ┆   ┆           ┆           ┆           ┆          │
│ kristians ┆ 3d51ec202 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ en…       ┆ 50c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 1a89fbd85 ┆ SRR111835 ┆ 0.857143  ┆ … ┆ 0.793388  ┆ 0.992686  ┆ 44        ┆ 986878   │
│ larctobac ┆ 86de8774a ┆ 49        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__Crypto ┆ add3c2f0c ┆ ERR113532 ┆ 1.0       ┆ … ┆ 0.771406  ┆ 1.0       ┆ 42        ┆ 5945435  │
│ bacteroid ┆ 370bea894 ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ es sp9005 ┆ a79ff0921 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 469…      ┆ 9bf…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Prevot ┆ eebb2e8cc ┆ ERR113532 ┆ 1.0       ┆ … ┆ 0.773406  ┆ 1.0       ┆ 80        ┆ 5945435  │
│ ella sp00 ┆ 777e470c0 ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0434975   ┆ 00f935e21 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 59e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Mogiba ┆ df2825263 ┆ ERR113532 ┆ 0.285714  ┆ … ┆ 0.728617  ┆ 0.942089  ┆ 2         ┆ 5945435  │
│ cterium_A ┆ c4d38115f ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ kristians ┆ 3d51ec202 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ en…       ┆ 50c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Lactob ┆ 750b12916 ┆ ERR113532 ┆ 0.833333  ┆ … ┆ 0.764738  ┆ 0.991356  ┆ 6         ┆ 5945435  │
│ acillus   ┆ e258ed448 ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ amylovoru ┆ fae467a19 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s         ┆ 0c8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ 4d5149fb1 ┆ ERR113532 ┆ 0.666667  ┆ … ┆ 0.756655  ┆ 0.980877  ┆ 12        ┆ 5945435  │
│ ricus sp0 ┆ c269db3d2 ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ caa4e0c8d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ db4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
len(df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD))

26562

In [7]:
for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent', descending=True).iter_rows(named=True):
    name = row['query_name']
    if name in CORENAMES:
        name = '** ' + name
    print(f"{row['percent']:.1f}% {name} ")

96.5% ** s__Sodaliphilus sp004557565
93.6% ** s__Bariatricus sp004560705
92.0% ** s__Lactobacillus amylovorus
91.5% ** s__Cryptobacteroides sp900546925
89.2% ** s__Prevotella sp002251295
82.4% ** s__Phascolarctobacterium_A succinatutens
82.1% ** s__Prevotella sp000434975
80.6% ** s__Mogibacterium_A kristiansenii
72.8% ** s__Holdemanella porci
45.2% ** s__JALFVM01 sp022787145

In [8]:
df

shape: (26_562, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__Sodali ┆ 73ffbc37a ┆ SRR111835 ┆ 0.857143  ┆ … ┆ 0.79599   ┆ 0.992686  ┆ 110       ┆ 999956   │
│ philus    ┆ dc473b43d ┆ 52        ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp0045575 ┆ 7588f0c7c ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 65        ┆ 591…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Prevot ┆ 46b9539c3 ┆ SRR111835 ┆ 0.125     ┆ … ┆ 0.728002  ┆ 0.905724  ┆ 1         ┆ 999956   │
│ ella sp00 ┆ 30b333990 ┆ 52        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2251295   ┆ 7e4eb0b5c ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 24b…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Crypto ┆ add3c2f0c ┆ SRR111835 ┆ 0.166667  ┆ … ┆ 0.734249  ┆ 0.918217  ┆ 2         ┆ 999956   │
│ bacteroid ┆ 370bea894 ┆ 52        ┆           ┆   ┆           ┆           ┆           ┆          │
│ es sp9005 ┆ a79ff0921 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 469…      ┆ 9bf…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Mogiba ┆ df2825263 ┆ SRR111835 ┆ 0.857143  ┆ … ┆ 0.79599   ┆ 0.992686  ┆ 29        ┆ 999956   │
│ cterium_A ┆ c4d38115f ┆ 52        ┆           ┆   ┆           ┆           ┆           ┆          │
│ kristians ┆ 3d51ec202 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ en…       ┆ 50c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 1a89fbd85 ┆ SRR111835 ┆ 0.857143  ┆ … ┆ 0.793388  ┆ 0.992686  ┆ 44        ┆ 986878   │
│ larctobac ┆ 86de8774a ┆ 49        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 2e3c85f3a ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 509…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__Crypto ┆ add3c2f0c ┆ ERR113532 ┆ 1.0       ┆ … ┆ 0.771406  ┆ 1.0       ┆ 42        ┆ 5945435  │
│ bacteroid ┆ 370bea894 ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ es sp9005 ┆ a79ff0921 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 469…      ┆ 9bf…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Prevot ┆ eebb2e8cc ┆ ERR113532 ┆ 1.0       ┆ … ┆ 0.773406  ┆ 1.0       ┆ 80        ┆ 5945435  │
│ ella sp00 ┆ 777e470c0 ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0434975   ┆ 00f935e21 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 59e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Mogiba ┆ df2825263 ┆ ERR113532 ┆ 0.285714  ┆ … ┆ 0.728617  ┆ 0.942089  ┆ 2         ┆ 5945435  │
│ cterium_A ┆ c4d38115f ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ kristians ┆ 3d51ec202 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ en…       ┆ 50c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Lactob ┆ 750b12916 ┆ ERR113532 ┆ 0.833333  ┆ … ┆ 0.764738  ┆ 0.991356  ┆ 6         ┆ 5945435  │
│ acillus   ┆ e258ed448 ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ amylovoru ┆ fae467a19 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s         ┆ 0c8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Bariat ┆ 4d5149fb1 ┆ ERR113532 ┆ 0.666667  ┆ … ┆ 0.756655  ┆ 0.980877  ┆ 12        ┆ 5945435  │
│ ricus sp0 ┆ c269db3d2 ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 04560705  ┆ caa4e0c8d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ db4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
SUB_SPECIES2=(
             's__Cryptobacteroides sp900546925',
             's__Phascolarctobacterium_A succinatutens',
             's__Mogibacterium_A kristiansenii',
             's__Prevotella sp002251295',
#             's__Prevotella sp000434975',
#             's__Holdemanella porci',
)

for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    if row["query_name"] in SUB_SPECIES2:
        print(f"{row['percent']:.1f}% {row['query_name']} ")

80.6% s__Mogibacterium_A kristiansenii
82.4% s__Phascolarctobacterium_A succinatutens
89.2% s__Prevotella sp002251295
91.5% s__Cryptobacteroides sp900546925

In [10]:
for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    print(f"{row['percent']:.1f}% {row['query_name']} ")

45.2% s__JALFVM01 sp022787145
72.8% s__Holdemanella porci
80.6% s__Mogibacterium_A kristiansenii
82.1% s__Prevotella sp000434975
82.4% s__Phascolarctobacterium_A succinatutens
89.2% s__Prevotella sp002251295
91.5% s__Cryptobacteroides sp900546925
92.0% s__Lactobacillus amylovorus
93.6% s__Bariatricus sp004560705
96.5% s__Sodaliphilus sp004557565