In [1]:
import polars as pl
import glob
import os.path

In [2]:
SCALED=1000
HASH_THRESHOLD=int(20000 / SCALED)
CONTAINMENT_THRESHOLD=0.01


#CSVPATH=f'../outputs.mapping/cds/singlehash.k21/outputs.3216.min{MIN}/manysearch.3216.csv'
CSVPATH=f'/home/ctbrown/scratch3/2025-workflow-core99/outputs.mapping/cds3/manysearch.3216.csv'

In [3]:
dflist = []
#ms_filenames = glob.glob('../manysearch-3216/*.cds.x.3216.manysearch.csv')
ms_filenames = glob.glob(CSVPATH)
for filename in ms_filenames:
    print(os.path.basename(filename))
    df = pl.read_csv(filename)
    dflist.append(df)

df = pl.concat(dflist)

manysearch.3216.csv

In [4]:
df

shape: (79_366, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__Prevot ┆ 11c2f06bb ┆ SRR111261 ┆ 0.102068  ┆ … ┆ 0.81684   ┆ 0.897025  ┆ 918       ┆ 906559   │
│ ella sp00 ┆ 0ba002567 ┆ 08        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2251295   ┆ a1bdc2a57 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 126…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__UMGS12 ┆ 32711230e ┆ SRR111261 ┆ 0.016775  ┆ … ┆ 0.725146  ┆ 0.823115  ┆ 22        ┆ 906559   │
│ 25 sp0340 ┆ bb0936ab5 ┆ 08        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 86705     ┆ 7ed263368 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 289…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Mogiba ┆ a6063c096 ┆ SRR111261 ┆ 0.101576  ┆ … ┆ 0.807123  ┆ 0.896818  ┆ 877       ┆ 906559   │
│ cterium_A ┆ 2c975db51 ┆ 08        ┆           ┆   ┆           ┆           ┆           ┆          │
│ kristians ┆ 4497f2715 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ en…       ┆ 11e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__JAFBIX ┆ 2902fdae1 ┆ SRR111261 ┆ 0.073482  ┆ … ┆ 0.793813  ┆ 0.883098  ┆ 268       ┆ 906559   │
│ 01 sp0215 ┆ da9e7a10d ┆ 08        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 31895     ┆ 826eac534 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 864…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ b8c6bbf95 ┆ SRR111261 ┆ 0.171033  ┆ … ┆ 0.814073  ┆ 0.919348  ┆ 792       ┆ 906559   │
│ larctobac ┆ 60cfc0876 ┆ 08        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 87eb69f00 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ b1c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__Rosebu ┆ f2654d4c2 ┆ ERR831475 ┆ 0.037142  ┆ … ┆ 0.749178  ┆ 0.854867  ┆ 931       ┆ 9259617  │
│ ria inuli ┆ e0a7a7447 ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ nivorans  ┆ 9c509794d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 10f…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__CAG-26 ┆ 078c4569f ┆ ERR831475 ┆ 0.009174  ┆ … ┆ 0.663594  ┆ 0.799797  ┆ 6         ┆ 9259617  │
│ 9 sp01484 ┆ 257f75356 ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6485      ┆ 832c47c16 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 808…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 8c3d1fa61 ┆ ERR831475 ┆ 0.010504  ┆ … ┆ 0.698393  ┆ 0.804969  ┆ 77        ┆ 9259617  │
│ larctobac ┆ d73093ded ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 0c14d4577 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 909…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Crypto ┆ 80c1ce43c ┆ ERR831475 ┆ 0.254972  ┆ … ┆ 0.817305  ┆ 0.936996  ┆ 6731      ┆ 9259617  │
│ bacteroid ┆ 8dff68ff8 ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ es sp9005 ┆ ec3e45dae ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 469…      ┆ 136…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Holdem ┆ 398766a16 ┆ ERR831475 ┆ 0.084355  ┆ … ┆ 0.754143  ┆ 0.888919  ┆ 955       ┆ 9259617  │
│ anella    ┆ d18d486ff ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ porci     ┆ 57f019d26 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 4e4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
df.sort(by='intersect_hashes').filter(pl.col("intersect_hashes") < 20)

shape: (20_716, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__Blauti ┆ 2d4c0d183 ┆ SRR111261 ┆ 0.001305  ┆ … ┆ 0.637705  ┆ 0.72888   ┆ 1         ┆ 906559   │
│ a_A sp945 ┆ 352faea54 ┆ 08        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 872375    ┆ d9921b1c3 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 1ed…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__CAG-87 ┆ c3683d020 ┆ SRR111834 ┆ 0.000541  ┆ … ┆ 0.621758  ┆ 0.698909  ┆ 4         ┆ 1048838  │
│ 3 sp01630 ┆ ea8ab7353 ┆ 28        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2215      ┆ 0e9c63b94 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 77e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__SIG351 ┆ deae0769a ┆ SRR111834 ┆ 0.000637  ┆ … ┆ 0.624511  ┆ 0.704413  ┆ 1         ┆ 1048838  │
│ sp9459187 ┆ 7f1129574 ┆ 28        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 95        ┆ 65b790cea ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ca8…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__CAG-46 ┆ dbf18ece4 ┆ SRR111255 ┆ 0.001088  ┆ … ┆ 0.632098  ┆ 0.722586  ┆ 1         ┆ 928016   │
│ 5 sp00043 ┆ 4eabc0166 ┆ 20        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3755      ┆ c4320733d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ea7…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 8c3d1fa61 ┆ SRR111255 ┆ 0.000233  ┆ … ┆ 0.606562  ┆ 0.671514  ┆ 1         ┆ 928016   │
│ larctobac ┆ d73093ded ┆ 20        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 0c14d4577 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 909…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__Rumino ┆ 1334e4747 ┆ ERR113536 ┆ 0.015833  ┆ … ┆ 0.695966  ┆ 0.820853  ┆ 58        ┆ 6286262  │
│ coccoides ┆ b950d31e4 ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp9027668 ┆ 4e3448e8b ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 85        ┆ 0fa…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Rumino ┆ fdc9ed9de ┆ SRR143692 ┆ 0.003929  ┆ … ┆ 0.676084  ┆ 0.768142  ┆ 48        ┆ 8506993  │
│ coccus_C  ┆ 30685c707 ┆ 02        ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp0004336 ┆ 7a1da7c8e ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 35        ┆ 64d…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 8c3d1fa61 ┆ ERR321204 ┆ 0.004435  ┆ … ┆ 0.68799   ┆ 0.772588  ┆ 43        ┆ 1659760  │
│ larctobac ┆ d73093ded ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 0c14d4577 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 909…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Prevot ┆ 4736bc318 ┆ SRR111250 ┆ 0.002797  ┆ … ┆ 0.684408  ┆ 0.755807  ┆ 25        ┆ 1420050  │
│ ella sp00 ┆ 783e81245 ┆ 51        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0434975   ┆ 554ed9fa2 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 61a…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Rumino ┆ 1334e4747 ┆ SRR172416 ┆ 0.015833  ┆ … ┆ 0.702237  ┆ 0.820853  ┆ 28        ┆ 14269973 │
│ coccoides ┆ b950d31e4 ┆ 68        ┆           ┆   ┆           ┆           ┆           ┆          │
│ sp9027668 ┆ 4e3448e8b ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 85        ┆ 0fa…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
len(df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD))

58650

In [7]:
for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    print(f"{row['percent']:.1f}% {row['query_name']} ")

19.6% s__Ruminococcoides sp902766885
20.6% s__CAG-465 sp000433755
22.4% s__Phascolarctobacterium_A succinatutens_B
28.8% s__CAG-269 sp014846485
34.1% s__CAG-873 sp016302215
34.3% s__Ventricola sp017937505
34.5% s__Blautia_A sp945872375
46.6% s__Bifidobacterium thermacidophilum
52.1% s__SIG351 sp945918795
57.2% s__Ruminococcus_C sp000433635
77.1% s__Roseburia inulinivorans
77.6% s__UMGS1225 sp034086705
82.7% s__Gemmiger qucibialis
87.6% s__Phascolarctobacterium_A succinatutens
90.1% s__Holdemanella porci
90.6% s__JALFVM01 sp022787145
93.8% s__Prevotella sp000434975
95.7% s__Bariatricus sp004560705
96.3% s__JAFBIX01 sp021531895
96.4% s__Prevotella sp002251295
96.7% s__UBA2868 sp004552595
97.0% s__Mogibacterium_A kristiansenii
97.1% s__Fimisoma sp002320005
97.5% s__Cryptobacteroides sp900546925
98.5% s__Lactobacillus amylovorus
99.0% s__Sodaliphilus sp004557565

In [8]:
for row in df.filter(pl.col("containment") >= CONTAINMENT_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    print(f"{row['percent']:.1f}% {row['query_name']} ")

5.0% s__Phascolarctobacterium_A succinatutens_B
31.6% s__CAG-465 sp000433755
32.9% s__Ruminococcoides sp902766885
34.4% s__CAG-873 sp016302215
38.9% s__Roseburia inulinivorans
42.1% s__Bifidobacterium thermacidophilum
43.2% s__CAG-269 sp014846485
45.7% s__Blautia_A sp945872375
48.2% s__Ruminococcus_C sp000433635
53.9% s__SIG351 sp945918795
55.1% s__Ventricola sp017937505
69.3% s__Gemmiger qucibialis
74.4% s__Prevotella sp000434975
81.7% s__UMGS1225 sp034086705
87.7% s__JALFVM01 sp022787145
87.7% s__UBA2868 sp004552595
90.9% s__JAFBIX01 sp021531895
91.6% s__Phascolarctobacterium_A succinatutens
93.0% s__Prevotella sp002251295
93.1% s__Holdemanella porci
93.5% s__Cryptobacteroides sp900546925
93.8% s__Mogibacterium_A kristiansenii
93.9% s__Bariatricus sp004560705
95.9% s__Lactobacillus amylovorus
97.2% s__Fimisoma sp002320005
97.4% s__Sodaliphilus sp004557565

In [9]:
df

shape: (79_366, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ query_nam ┆ query_md5 ┆ match_nam ┆ containme ┆ … ┆ average_c ┆ max_conta ┆ n_weighte ┆ total_we │
│ e         ┆ ---       ┆ e         ┆ nt        ┆   ┆ ontainmen ┆ inment_an ┆ d_found   ┆ ighted_h │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ t_ani     ┆ i         ┆ ---       ┆ ashes    │
│ str       ┆           ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ s__Prevot ┆ 11c2f06bb ┆ SRR111261 ┆ 0.102068  ┆ … ┆ 0.81684   ┆ 0.897025  ┆ 918       ┆ 906559   │
│ ella sp00 ┆ 0ba002567 ┆ 08        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2251295   ┆ a1bdc2a57 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 126…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__UMGS12 ┆ 32711230e ┆ SRR111261 ┆ 0.016775  ┆ … ┆ 0.725146  ┆ 0.823115  ┆ 22        ┆ 906559   │
│ 25 sp0340 ┆ bb0936ab5 ┆ 08        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 86705     ┆ 7ed263368 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 289…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Mogiba ┆ a6063c096 ┆ SRR111261 ┆ 0.101576  ┆ … ┆ 0.807123  ┆ 0.896818  ┆ 877       ┆ 906559   │
│ cterium_A ┆ 2c975db51 ┆ 08        ┆           ┆   ┆           ┆           ┆           ┆          │
│ kristians ┆ 4497f2715 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ en…       ┆ 11e…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__JAFBIX ┆ 2902fdae1 ┆ SRR111261 ┆ 0.073482  ┆ … ┆ 0.793813  ┆ 0.883098  ┆ 268       ┆ 906559   │
│ 01 sp0215 ┆ da9e7a10d ┆ 08        ┆           ┆   ┆           ┆           ┆           ┆          │
│ 31895     ┆ 826eac534 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 864…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ b8c6bbf95 ┆ SRR111261 ┆ 0.171033  ┆ … ┆ 0.814073  ┆ 0.919348  ┆ 792       ┆ 906559   │
│ larctobac ┆ 60cfc0876 ┆ 08        ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 87eb69f00 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ b1c…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ s__Rosebu ┆ f2654d4c2 ┆ ERR831475 ┆ 0.037142  ┆ … ┆ 0.749178  ┆ 0.854867  ┆ 931       ┆ 9259617  │
│ ria inuli ┆ e0a7a7447 ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ nivorans  ┆ 9c509794d ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 10f…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__CAG-26 ┆ 078c4569f ┆ ERR831475 ┆ 0.009174  ┆ … ┆ 0.663594  ┆ 0.799797  ┆ 6         ┆ 9259617  │
│ 9 sp01484 ┆ 257f75356 ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6485      ┆ 832c47c16 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 808…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Phasco ┆ 8c3d1fa61 ┆ ERR831475 ┆ 0.010504  ┆ … ┆ 0.698393  ┆ 0.804969  ┆ 77        ┆ 9259617  │
│ larctobac ┆ d73093ded ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ terium_A  ┆ 0c14d4577 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ suc…      ┆ 909…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Crypto ┆ 80c1ce43c ┆ ERR831475 ┆ 0.254972  ┆ … ┆ 0.817305  ┆ 0.936996  ┆ 6731      ┆ 9259617  │
│ bacteroid ┆ 8dff68ff8 ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ es sp9005 ┆ ec3e45dae ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 469…      ┆ 136…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ s__Holdem ┆ 398766a16 ┆ ERR831475 ┆ 0.084355  ┆ … ┆ 0.754143  ┆ 0.888919  ┆ 955       ┆ 9259617  │
│ anella    ┆ d18d486ff ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ porci     ┆ 57f019d26 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 4e4…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
SUB_SPECIES2=(
             's__Cryptobacteroides sp900546925',
             's__Phascolarctobacterium_A succinatutens',
             's__Mogibacterium_A kristiansenii',
             's__Prevotella sp002251295',
#             's__Prevotella sp000434975',
#             's__Holdemanella porci',
)

for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    if row["query_name"] in SUB_SPECIES2:
        print(f"{row['percent']:.1f}% {row['query_name']} ")

87.6% s__Phascolarctobacterium_A succinatutens
96.4% s__Prevotella sp002251295
97.0% s__Mogibacterium_A kristiansenii
97.5% s__Cryptobacteroides sp900546925

In [11]:
for row in df.filter(pl.col("intersect_hashes") >= HASH_THRESHOLD)['query_name'].value_counts().with_columns(
    (pl.col("count") / 3216 * 100).alias("percent")
).sort(by='percent').iter_rows(named=True):
    print(f"{row['percent']:.1f}% {row['query_name']} ")

19.6% s__Ruminococcoides sp902766885
20.6% s__CAG-465 sp000433755
22.4% s__Phascolarctobacterium_A succinatutens_B
28.8% s__CAG-269 sp014846485
34.1% s__CAG-873 sp016302215
34.3% s__Ventricola sp017937505
34.5% s__Blautia_A sp945872375
46.6% s__Bifidobacterium thermacidophilum
52.1% s__SIG351 sp945918795
57.2% s__Ruminococcus_C sp000433635
77.1% s__Roseburia inulinivorans
77.6% s__UMGS1225 sp034086705
82.7% s__Gemmiger qucibialis
87.6% s__Phascolarctobacterium_A succinatutens
90.1% s__Holdemanella porci
90.6% s__JALFVM01 sp022787145
93.8% s__Prevotella sp000434975
95.7% s__Bariatricus sp004560705
96.3% s__JAFBIX01 sp021531895
96.4% s__Prevotella sp002251295
96.7% s__UBA2868 sp004552595
97.0% s__Mogibacterium_A kristiansenii
97.1% s__Fimisoma sp002320005
97.5% s__Cryptobacteroides sp900546925
98.5% s__Lactobacillus amylovorus
99.0% s__Sodaliphilus sp004557565